apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-actions-runner-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    creationPolicy: Owner
  data:
    - secretKey: github_app_id
      remoteRef:
        key: github/app/ActionsRunnerController
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: github/app/ActionsRunnerController
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: github/app/ActionsRunnerController
        property: github_app_private_key
