apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager
  # Finalizer that ensures that project is not deleted until it is not referenced by any pre-stg
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"